on:
  pull_request:
    branches:
      - 'main'
    types: [closed]
name: tag release 
jobs:
  tag-release:
    if: github.event.pull_request.merged && startsWith( github.head_ref, 'release-' )
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: tag
      run: |-
        echo ${{ github.head_ref }}
        set -e
        BRANCH_NAME=${{ github.head_ref }}
        SEMVER_TAG=${BRANCH_NAME: -6}
        echo $SEMVER_TAG
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git tag -a $SEMVER_TAG -m "release $SEMVER_TAG"
        git push origin $SEMVER_TAG
